### ISSUE TITLE
Use machine-readable error log

### ISSUE THREAD

**Issue by valery1707** [valery1707/kaitai-maven-plugin#14]
As described in https://github.com/kaitai-io/kaitai_struct/issues/509#issuecomment-454022525, using key `--ksc-json-output` will produce more detailed output.

DemoKSY:
```
meta:
  id: demo
  file-extension: demo
  endian: le
seq:
  - id: header
    type: header
types:
  header:
    seq:
      - id: Magic
        contents: 'DEMO'
```

Human: `/types/header/seq/0/id: invalid attribute ID: 'Magic', expected /^[a-z][a-z0-9_]*$/`
Machine (formatted): 
```json
{
  "src\\it\\it-source-failed\\src\\main\\resources\\kaitai\\demo.ksy": {
    "errors": [
      {
        "file": "(main)",
        "path": ["types", "header", "seq", "0", "id"],
        "message": "invalid attribute ID: 'Magic', expected /^[a-z][a-z0-9_]*$/"
      }
    ]
  }
}
```
